# Generated by Django 4.0.1 on 2022-01-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='email',
            field=models.CharField(default="null", max_length=20),
        ),
    ]
