# Generated by Django 4.0.1 on 2022-01-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0002_myuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.CharField(max_length=20),
        ),
    ]
