# Generated by Django 4.0.1 on 2022-02-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0003_alter_myuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('track', models.CharField(max_length=20)),
            ],
        ),
    ]
